steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/gcloud']

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'ci' ]

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'test' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['info']
  timeout: 500s