version: '3'
services:
  web:
    image: botium/botium-box-ce:box-latest
    ports:
     - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/box/ce
      BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
      DEBUG: botium*
    depends_on:
      - redis
      - prisma
    volumes:
      - testsets:/spec
      - botiumwork:/botiumwork
  prisma:
    image: prismagraphql/prisma:1.25.4
    depends_on:
      - mysql
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
    ports:
    - "6379:6379"
volumes:
  mysql:
  testsets:
  botiumwork:
